### ISSUE TITLE
이거 설치 어떻게 하나요?

### ISSUE THREAD

**Issue by JeonDohyeon** [aaei924/NamuMark#2]
ㅈㄱㄴ

정확히는 LocalSettings.php에 어떻게 입력해야 하나요?
README.MD에 안 적혀 있어서..

**Comment by aaei924** [comment]
본 파서는 미디어위키용이 아닙니다.

(토론 관련해서 언급한 것은 자체 개발 중인 엔진을 위한 것입니다)

**Comment by JeonDohyeon** [comment]
알겠습니다. 이슈 닫겠습니다.
